# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testloginvalid(self):
    self.driver.get("https://www.saucedemo.com/inventory.html/")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/inventory.html")
  
  def test_testcheckoutinfovalid(self):
    self.driver.get("https://www.saucedemo.com/checkout-step-one.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys("J")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys("B")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys("ABC")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/checkout-step-two.html")
  
  def test_testcheckoutproduct(self):
    self.driver.get("https://www.saucedemo.com/inventory.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/cart.html")
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").text == "Sauce Labs Backpack"
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/checkout-step-one.html")
  
  def test_testlogininvalid(self):
    self.driver.get("https://www.saucedemo.com/inventory.html/")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("bad_password")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/")
  
  def test_testlogout(self):
    self.driver.get("https://www.saucedemo.com/inventory.html")
    self.driver.find_element(By.ID, "react-burger-menu-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"logout-sidebar-link\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/")
  
  def test_testplaceorder(self):
    self.driver.get("https://www.saucedemo.com/checkout-step-two.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/checkout-complete.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/inventory.html")
  
  def test_testviewproduct(self):
    self.driver.get("https://www.saucedemo.com/inventory.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/inventory-item.html?id=4")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/inventory.html")
  
  def test_testaddandremoveproduct(self):
    self.driver.get("https://www.saucedemo.com/inventory.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"shopping-cart-link\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-backpack\"]").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]")
    assert len(elements) == 0
  
  def test_testcheckoutinfoempty(self):
    self.driver.get("https://www.saucedemo.com/checkout-step-one.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()
    self.vars["newURL"] = self.driver.execute_script("return document.URL;")
    assert(self.vars["newURL"] == "https://www.saucedemo.com/checkout-step-one.html")
  
  def test_testfilter(self):
    self.driver.get("https://www.saucedemo.com/inventory.html")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product-sort-container\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").text == "Sauce Labs Backpack"
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product-sort-container\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").text == "Test.allTheThings() T-Shirt (Red)"
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product-sort-container\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").text == "Sauce Labs Onesie"
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product-sort-container\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(4)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"inventory-item-name\"]").text == "Sauce Labs Fleece Jacket"
  
