# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcheckbox1andcheckbox2(self):
    self.driver.get("https://the-internet.herokuapp.com/checkboxes")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").is_selected() is False
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").is_selected() is False
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").is_selected() is True
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").is_selected() is True
  
  def test_testcheckbox1(self):
    self.driver.get("https://the-internet.herokuapp.com/checkboxes")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").is_selected() is True
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").is_selected() is True
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").is_selected() is False
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").is_selected() is True
  
  def test_testcheckbox2(self):
    self.driver.get("https://the-internet.herokuapp.com/checkboxes")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").is_selected() is False
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").is_selected() is False
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").is_selected() is True
    assert self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").is_selected() is False
  
