# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testselectoption1(self):
    self.driver.get("https://the-internet.herokuapp.com/dropdown")
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 1"
  
  def test_testoptionspresent(self):
    self.driver.get("https://the-internet.herokuapp.com/dropdown")
    assert self.driver.find_element(By.ID, "dropdown").text == "Please select an option\\\\nOption 1\\\\nOption 2"
  
  def test_testselectoption2(self):
    self.driver.get("https://the-internet.herokuapp.com/dropdown")
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 2"
  
  def test_testswitchtooption1(self):
    self.driver.get("https://the-internet.herokuapp.com/dropdown")
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 1"
  
  def test_testswitchtooption2(self):
    self.driver.get("https://the-internet.herokuapp.com/dropdown")
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 2"
  
  def test_testselectoption1fromoption1(self):
    self.driver.get("https://the-internet.herokuapp.com/dropdown")
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 1"
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 1"
  
  def test_testselectoption2fromoption2(self):
    self.driver.get("https://the-internet.herokuapp.com/dropdown")
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 2"
    self.driver.find_element(By.ID, "dropdown").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    element = self.driver.find_element(By.ID, "dropdown")
    locator = "option[@value='{}']".format(element.get_attribute("value"))
    selected_text = element.find_element(By.XPATH, locator).text
    assert selected_text == "Option 2"
  
